import "./mutual.js";
import "./local-storage-manager.js";
import "./switches.js";
import "./add-task.js";
import "./check-tasks.js";
import "./delete-tasks.js";
import "./edit-task.js";
import "./task-preview.js";
import "./theme-switcher.js";
